### ISSUE TITLE
More concrete normative requirements

### ISSUE THREAD

**Issue by danielfett** [oauth-wg/oauth-cross-device-security#116]
We should add more concrete normative guidance for implementers. For example:

- Implementers MUST perform a risk assessment before implementing cross-device flows, weighing the risks (from these attacks) against benefits for users.
- SHOULD avoid cross-device flows if risks cannot be sufficiently mitigated.
- must follow the guidance provided in Section 5.2.4 for protocol selection (→ we could pull 5.2.4 into this section here)
- MUST implement mitigations appropriate for the use case, architecture, and selected protocols (as listed in Section 5.1)
- SHOULD implement proximity checks as defined in Section 5.1.1 if possible

**Comment by PieterKas** [comment]
Addressed in PR #117
