### ISSUE TITLE
Fix conference and journal name in some references

### ISSUE THREAD

**Issue by marcopernpruner** [oauth-wg/oauth-cross-device-security#143]
The following references need to be fixed:

- `MPRCS2020`: the title of the proceedings in which the paper has been published currently appears as "IEEE Proceedings of the Tenth ACM Conference on Data and Application Security and Privacy". However, it should be "Proceedings of the Tenth ACM Conference on Data and Application Security and Privacy", since the conference is not IEEE.
- `PCRSM2023`: the name of the journal in which the paper has been published currently appears as "IEEE IEEE Transactions on Dependable and Secure Computing" (double "IEEE").

**Comment by PieterKas** [comment]
Fixed issue in latest PR
