### ISSUE TITLE
Near device versus cross device

### ISSUE THREAD

**Issue by damienbod** [oauth-wg/oauth-cross-device-security#45]
I have trouble explaining why scanning a QR code is dangerous to initialize authentication flows to gain access because sometimes it is less dangerous. When using a device which is close proximity to the second device and forcing this through a protocol, the danger is reduced. I think introducing a new wording context would help (especially if this was used in the corresponding protocols, for example FIDO2 passkeys)

**Near device**
A device which is in close proximity to the second device and uses a protocol which forces a close proximity communication channel for the authentication steps.

**Cross device**
A device which communicates to a separate device and uses a protocol which does not force proximity to the second device.

Then it would be easy to explain attacks and mitigations:

_Using a near device communication, the attack X is not possible etc._

Not sure this is the right place to add this, but it would help I think.

**Comment by PieterKas** [comment]
That's and interesting idea. To me it is more about cross-device protocol properties. Some of them have strong proximity assurance properties, and some don't. 

Perhaps terminology like "proximity verified cross-device flows" or "proximity enforced cross device flows" vs "proximity-less cross device flows" works better? It is also somewhat protocol neutral.

**Comment by damienbod** [comment]
I like these two:  "proximity enforced cross device flows" vs "proximity-less cross device flows"

**Comment by PieterKas** [comment]
Let me think about how to work that terminology into the text at the right places.
